"""empty message

Revision ID: 4ba097163520
Revises: 9ee2760b94f7
Create Date: 2021-08-25 21:25:57.042581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba097163520'
down_revision = '9ee2760b94f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'branch', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'vehicle_id')
    # ### end Alembic commands ###
