"""empty message

Revision ID: 9ee2760b94f7
Revises: db7746b7cceb
Create Date: 2021-08-25 21:16:55.424941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee2760b94f7'
down_revision = 'db7746b7cceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'vehicle_id')
    # ### end Alembic commands ###
